--insert into loja (nome, endereco) values ('' , '')
insert into loja (nome, endereco) values ('Pão de Açúcar aguananmbi' , 'R. Bárbara de Alencar - Aldeota, Fortaleza - CE, 60140-000')
insert into loja (nome, endereco) values ('Makro' , 'Av. Alberto Craveiro, 507 - Dias Macedo, Fortaleza - CE, 60860-000')
insert into loja (nome, endereco) values ('Assaí Atacadista - Mister Hull' , 'Assaí Atacadista - Mister Hull')
insert into loja (nome, endereco) values ('Atacadão - Fortaleza Aeroporto' , 'Av. Senador Carlos Jereissati, 3001 - Serrinha, Fortaleza - CE, 60741-215')
insert into loja (nome, endereco) values ('Atacadão Lag' , 'Av. Bernardo Manuel, 11000 - Mondubim, Fortaleza - CE, 60761-740')	
insert into loja (nome, endereco) values ('Mix Mateus caucaia' , 'Av. Dom Almeida Lustosa, 1989 - Parque Guadalajara, Caucaia - CE, 61645-000')
insert into loja (nome, endereco) values ('Mix Mateus - Maracanaú' , 'Av. Dr. Mendel Steinbruch, 14000 - Distrito Industrial I, Maracanaú - CE')
insert into loja (nome, endereco) values ('Assai parangaba' , 'Av. Godofredo Maciel, 86 - Parangaba, Fortaleza - CE, 60710-000')
insert into loja (nome, endereco) values ('Mercadão São Luiz - RioMar Kennedy' , ' Av. Srg. Hermínio Sampaio, 3100 - L1 loja 1036 - Pres. Kennedy, Fortaleza - CE, 60355-512')